# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/_tflow_select-2.1.0-gpu.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.4.13-h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-9.2-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-3.0.0-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudnn-7.6.5-cuda9.2_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cupti-9.2.148-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.17.1-h27cfd23_0.conda
https://conda.anaconda.org/conda-forge/linux-64/graphite2-1.3.13-h58526e2_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.2-hf484d3e_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.2.1-hf484d3e_1007.conda
https://conda.anaconda.org/conda-forge/linux-64/libglu-9.0.0-he1b5a44_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.16-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libopus-1.3.1-h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libvpx-1.7.0-h439df22_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.44-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.38.0-h516909a_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h36c2ea0_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-inputproto-2.3.2-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libice-1.0.10-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.9-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-hf34092f_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.2-hc401514_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20210216-h27cfd23_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.14.0-h8c45485_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h14c3975_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.10-hb55368b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-7.0-h7b6447c_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xorg-fixesproto-5.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.9-haebb681_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.33.0-h62c20be_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xorg-libx11-1.6.12-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ffmpeg-4.0-hcdf2ecd_0.conda
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-he4413a7_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.8-h0371630_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxext-1.3.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxfixes-5.0.3-h516909a_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/astor-0.8.1-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.12.5-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/coverage-5.5-py36h27cfd23_2.conda
https://repo.anaconda.com/pkgs/main/noarch/gast-0.4.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py36_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.6-1_cp36m.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/six-1.15.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/termcolor-1.1.0-py36h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-pyha847dfd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/werkzeug-1.0.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxi-1.7.10-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/zipp-3.4.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/absl-py-0.12.0-py36h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/freeglut-3.2.1-h58526e2_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.58.3-py36hd3ed26a_1004.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-3.10.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py36he8ac12f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-8.2.0-py36he98fc37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-52.0.0-py36h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.16.0-h18b612c_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cython-0.29.23-py36h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jasper-2.0.14-h07fcdf6_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.3.4-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.2-py36hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-21.0.1-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/protobuf-3.14.0-py36h2531618_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/grpcio-1.36.1-py36h2157cd5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/harfbuzz-1.8.8-hffaf4a1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libopencv-3.4.2-hb342d67_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.0-py36h54f3939_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py36h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.2-py36h54aff64_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/py-opencv-3.4.2-py36hb342d67_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.5.2-py36h0b6359f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-1.10.0-py36hf484d3e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-base-1.10.0-gpu_py36had579c0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/opencv-3.4.2-py36h6fd60c2_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-1.10.0-gpu_py36hcebf108_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-gpu-1.10.0-hf154084_0.conda
