# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/pytorch/linux-64/cuda90-1.0-h6433d27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-9.0-h13b8566_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.1.19-h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.3.0-h2531618_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.14-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.44-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.1.7-had09818_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.68.0-h36276a3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.10-hb55368b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.1-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.9-haebb681_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-h28cd5cc_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.35.4-hdfb4753_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.1-h6c09931_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-h8213a91_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-2.7.18-h15b4118_1.conda
https://repo.anaconda.com/pkgs/main/noarch/asn1crypto-1.4.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backports-1.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/backports_abc-0.5-py_1.conda
https://repo.anaconda.com/pkgs/main/noarch/certifi-2020.6.20-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/chardet-3.0.4-py27_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.2.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dask-core-1.2.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/enum34-1.1.6-py27_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/functools32-3.2.3.2-py27_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/futures-3.3.0-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/idna-2.10-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/ipaddress-1.0.23-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipython_genutils-0.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.1.0-py27he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.9.0-py27hfd86e86_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.2-py27h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.9.7-h5867ecd_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/scandir-1.10.0-py27h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/simplegeneric-0.8.1-py27_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.19.8-py27hf484d3e_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.15.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/subprocess32-3.5.4-py27h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.10.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backports.shutil_get_terminal_size-1.0.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.0-py27he30daa8_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py27_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.10.1-py27h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py27he904b0f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pathlib2-2.3.5-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-6.2.1-py27h34e0f95_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.9.2-py27h05f1152_2.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-44.0.0-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/singledispatch-3.6.1-pyhd3eb1b0_1001.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-4.3.3-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backports.functools_lru_cache-1.6.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-2.8-py27h1ba5d50_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-2.2-py27_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nltk-3.4.5-py27_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.16.6-py27hde5b4d6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py27_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-19.3.1-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.5.2-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-5.1.1-py27h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt_toolkit-1.0.15-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyopenssl-20.0.1-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-5.8.0-py27_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.25.7-py27_0.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-2.25.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/imageio-2.6.1-py27_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.3-py27hb69df0a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.15-py27ha843d7b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.0-py27hd6b4f25_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.16.6-py27hbc911f0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-0.24.2-py27he6710b0_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-0.4.1-py27__9.0.176_7.1.2_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pywavelets-1.0.3-py27hdd07704_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.2.1-py27h7c811a0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-image-0.14.2-py27he6710b0_0.conda
https://conda.anaconda.org/pytorch/noarch/torchvision-0.2.1-py_2.tar.bz2
