# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.4.13-h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-10.2.89-hfd86e86_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.2.1-h2531618_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lame-3.100-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.15-h63c8f33_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtasn1-4.16.0-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libunistring-0.9.10-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuv-1.40.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.10.2-hff7bd54_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libidn2-2.3.0-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nettle-3.7.2-hbbd107a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openh264-2.1.0-hd408876_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.1-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.9-haebb681_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gnutls-3.6.15-he1e5248_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.35.4-hdfb4753_0.conda
https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.10-h7579374_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.12.5-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/click-7.1.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.6.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dask-core-1.1.4-py36_1.conda
https://repo.anaconda.com/pkgs/main/noarch/dataclasses-0.8-pyh4f3eec9_6.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.0.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.3.1-py36h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py36_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/regex-2021.4.4-py36h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/six-1.15.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.1-py36h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.59.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-pyha847dfd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py36_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.11.0-py36h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py36he8ac12f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-8.2.0-py36he98fc37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-52.0.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-2.2-py36_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.2-py36hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-21.0.1-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nltk-3.6.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.3.4-py36h62a2d02_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.0-py36h54f3939_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py36h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.2-py36h54aff64_0.conda
https://repo.anaconda.com/pkgs/main/noarch/imageio-2.9.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.1.3-py36he6710b0_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-1.8.1-py3.6_cuda10.2_cudnn7.6.5_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pywavelets-1.1.1-py36h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.5.2-py36h0b6359f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tifffile-2020.10.1-py36hdd07704_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-image-0.17.2-py36hdf5156a_0.conda
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.9.1-py36_cu102.tar.bz2
