# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.4.13-h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-9.0-h13b8566_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2019.4-243.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudnn-7.6.5-cuda9.0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2018.0.3-1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.3.0-h2531618_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/freeglut-3.0.0-hf484d3e_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/graphite2-1.3.14-h23475e2_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libglu-9.0.0-hf484d3e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libopus-1.3.1-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libvpx-1.7.0-h439df22_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.14-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nccl-1.3.5-cuda9.0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.10.2-hff7bd54_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.44-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pixman-0.40.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2020.3-hfd86e86_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.68.1-h36276a3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.2-hba1933b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jasper-2.0.14-h07fcdf6_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.10-hb55368b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.1-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.9-haebb681_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-h28cd5cc_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.35.4-hdfb4753_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ffmpeg-4.0-hcdf2ecd_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.1-h6c09931_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-h8213a91_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.13-hdb3f193_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cairo-1.16.0-hf32fb01_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.12.5-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.6.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.0.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.3.1-py36h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py36_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.4.1-py36h27cfd23_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.9.7-h5867ecd_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.19.8-py36hf484d3e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/six-1.15.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb4py-2020.3-py36hfd86e86_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.1.0-pyh5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.1-py36h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.5-py36h261ae71_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py36_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.11.0-py36h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dask-core-2021.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/harfbuzz-1.8.8-hffaf4a1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.15.4-py36h81de0dd_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-8.2.0-py36he98fc37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.9.2-py36h05f1152_2.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-52.0.0-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libopencv-3.4.2-hb342d67_1.conda
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-21.0.1-py36h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/h5py-2.8.0-py36h989c5e5_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.3.2-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.3.2-py36h817c723_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.6-py36h7dd41cf_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.0.1-py36h4414c95_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.15.4-py36h1d66e8a_0.conda
https://repo.anaconda.com/pkgs/main/noarch/imageio-2.9.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/py-opencv-3.4.2-py36hb342d67_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytorch-0.4.0-py36hdf912b8_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pywavelets-1.1.1-py36h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-0.19.1-py36h9976243_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/opencv-3.4.2-py36h6fd60c2_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-image-0.16.2-py36h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-0.23.2-py36h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/torchvision-0.2.1-py36_0.conda
